export const ADD_COUNTER = 'add_counter'
export const ADD_TO_CART = 'add_to_cart'
export const CHANGE_CHECKED = 'changeChecked'
export const CHANGE_CHECKED_TRUE = 'changeCheckedTrue'
export const CHANGE_CHECKED_FALSE = 'changeCheckedFalse'
export const DEL_ORDER = 'delOrder'
export const SET_USER = 'setUser'